// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortConnect() {
  return window['go']['wailsapp']['App']['AbortConnect']();
}

export function AddGroupServer(arg1, arg2) {
  return window['go']['wailsapp']['App']['AddGroupServer'](arg1, arg2);
}

export function BulkPingAll() {
  return window['go']['wailsapp']['App']['BulkPingAll']();
}

export function ClearPinnedError() {
  return window['go']['wailsapp']['App']['ClearPinnedError']();
}

export function Connect() {
  return window['go']['wailsapp']['App']['Connect']();
}

export function ConnectAction() {
  return window['go']['wailsapp']['App']['ConnectAction']();
}

export function Disconnect() {
  return window['go']['wailsapp']['App']['Disconnect']();
}

export function ExportLog() {
  return window['go']['wailsapp']['App']['ExportLog']();
}

export function GetConnectionSnapshot() {
  return window['go']['wailsapp']['App']['GetConnectionSnapshot']();
}

export function GetRouteQuick() {
  return window['go']['wailsapp']['App']['GetRouteQuick']();
}

export function GetSettingsSnapshot() {
  return window['go']['wailsapp']['App']['GetSettingsSnapshot']();
}

export function GroupKinds() {
  return window['go']['wailsapp']['App']['GroupKinds']();
}

export function HideWindow() {
  return window['go']['wailsapp']['App']['HideWindow']();
}

export function ListGroups() {
  return window['go']['wailsapp']['App']['ListGroups']();
}

export function ListProfiles() {
  return window['go']['wailsapp']['App']['ListProfiles']();
}

export function LoadSettingsJSON() {
  return window['go']['wailsapp']['App']['LoadSettingsJSON']();
}

export function Ping() {
  return window['go']['wailsapp']['App']['Ping']();
}

export function Quit() {
  return window['go']['wailsapp']['App']['Quit']();
}

export function RefreshGroup(arg1) {
  return window['go']['wailsapp']['App']['RefreshGroup'](arg1);
}

export function ReloadMihomo() {
  return window['go']['wailsapp']['App']['ReloadMihomo']();
}

export function SaveSettingsJSON(arg1) {
  return window['go']['wailsapp']['App']['SaveSettingsJSON'](arg1);
}

export function SetRouteQuick(arg1) {
  return window['go']['wailsapp']['App']['SetRouteQuick'](arg1);
}

export function ShowWindow() {
  return window['go']['wailsapp']['App']['ShowWindow']();
}

export function SocketPath() {
  return window['go']['wailsapp']['App']['SocketPath']();
}

export function StartDaemon() {
  return window['go']['wailsapp']['App']['StartDaemon']();
}

export function StopDaemon() {
  return window['go']['wailsapp']['App']['StopDaemon']();
}

export function UpdateGroupSubscription(arg1, arg2) {
  return window['go']['wailsapp']['App']['UpdateGroupSubscription'](arg1, arg2);
}
