// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsapp} from '../models';

export function AbortConnect():Promise<void>;

export function AddGroupServer(arg1:number,arg2:string):Promise<void>;

export function BulkPingAll():Promise<string>;

export function ClearPinnedError():Promise<void>;

export function Connect():Promise<string>;

export function ConnectAction():Promise<string>;

export function Disconnect():Promise<string>;

export function ExportLog():Promise<string>;

export function GetConnectionSnapshot():Promise<wailsapp.ConnectionDTO>;

export function GetRouteQuick():Promise<number>;

export function GetSettingsSnapshot():Promise<wailsapp.SettingsDTO>;

export function GroupKinds():Promise<Array<string>>;

export function HideWindow():Promise<void>;

export function ListGroups():Promise<Array<wailsapp.GroupDTO>>;

export function ListProfiles():Promise<Array<wailsapp.ProfileDTO>>;

export function LoadSettingsJSON():Promise<Record<string, any>>;

export function Ping():Promise<wailsapp.PingResultDTO>;

export function Quit():Promise<void>;

export function RefreshGroup(arg1:number):Promise<string>;

export function ReloadMihomo():Promise<void>;

export function SaveSettingsJSON(arg1:Record<string, any>):Promise<void>;

export function SetRouteQuick(arg1:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function SocketPath():Promise<string>;

export function StartDaemon():Promise<void>;

export function StopDaemon():Promise<void>;

export function UpdateGroupSubscription(arg1:number,arg2:string):Promise<void>;
